### PR TITLE
Collaborative writing of SC abstract for RSE in HPC workshop at SC'23

### PR DESCRIPTION
**Pull request by samumantha**
A rough first draft, mainly puzzled together from other abstracts. In parentheses I left the general topics that maybe should be somewhere in the abstract (?), those should be removed later.

Please do not feel bad if you want to completely rewrite. This is just meant as starting point.
@bast

### CODE REVIEW

**Comment by bast** [comment]
Thanks so much! :hammer_and_pick:

**Comment by bast** [comment]
Made an editing round. We need a title. I made a suggestion but please check whether you like it.

**Comment by samumantha** [comment]
Also did another round with small edit suggestions and removed the section titles.

**Comment by samumantha** [comment]
For the Title, does research software need to be in there? 
"CodeRefinery: Training researchers and RSEs in FAIR research software tools and practices"

**Comment by bast** [comment]
> CodeRefinery: Training researchers and RSEs in FAIR research software tools and practices

the new title is better - thanks

**Comment by samumantha** [comment]
Ah and sorry for editing directly, should have put suggestions for the changes in text. Did not cross my mind in the moment as I did these last ones from phone. 

The last sentence fix was a try to split that long sentence into two, but maybe it is also not needed.

**Comment by bast** [comment]
No problem at all. I did the same. I should also have made suggestion changes. All good. I will sleep on it, tomorrow make another round and then submit.

**Pull request merged**
